# Generated by Django 3.2.2 on 2021-05-09 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flood', '0002_alter_person_pincode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='pincode',
            field=models.CharField(max_length=10),
        ),
    ]
